### ISSUE TITLE
Slash inside track's name leads to wrong page on last.fm

### ISSUE THREAD

**Issue by ex47** [david-sabata/web-scrobbler#1007]
If there is slash inside a track's name then 'view on track on last.fm' link leads to wrong page.
![screenshot_9](https://cloud.githubusercontent.com/assets/2480069/17267742/d10d9336-5619-11e6-8879-9050e2f74900.png)
e.g.: 
- correct page - http://www.last.fm/music/Daughter/_/aLONe+%2F+wiTh+YOU
- page where you actually land - http://www.last.fm/music/Daughter/_/aLONe+/+wiTh+YOU

**Comment by alexesprit** [comment]
I think it's Last.fm fail, not Web scrobbler.

Last.fm has "broken" https links. See the difference between two ones:
* http://www.last.fm/music/Daughter/_/aLONe+%2F+wiTh+YOU
* https://www.last.fm/music/Daughter/_/aLONe+%2F+wiTh+YOU

The first link is same as in your comment. The second one is provided by Last.fm API.

It's also intresting that the second secured link redirects to unsecured one. 

Of course, it's possibly can be fixed by replacing "https" to "http" in the string containing a link to a song; but it's a dirty hack.

**Comment by alexesprit** [comment]
Seems like Last.fm were fixed it. Now both links are valid.
