### ISSUE TITLE
Wrong connector title in "now playing" notifications

### ISSUE THREAD

**Issue by ex47** [david-sabata/web-scrobbler#1020]
Every connector placed inside `connectors.js` after:

```
        {
            label: 'Sonerezh',
            matches: ['*://sonerezh.*/*', '*://*/*sonerezh*'],
            js: ['connectors/v2/sonerezh.js'],
            version: 2
        }
```

is shown as
![screenshot_8](https://cloud.githubusercontent.com/assets/2480069/17516719/ca3f9bc6-5e48-11e6-98f3-5b5130a9846f.png)

Looks like this part inside `song.js` particularly likes `['*://sonerezh.*/*', '*://*/*sonerezh*']`
![screenshot_9](https://cloud.githubusercontent.com/assets/2480069/17516816/4c8600d4-5e49-11e6-908c-88807a597726.png)

**Comment by alexesprit** [comment]
Looks like URL match patterns are little tricky. I tried to use `Inject.createPattern` function instead of `RoutePattern.fromString` one, works well. But I don't think copypasting of `Inject.createPattern` function is a good solution.

Also this code block can be simplified to:
```js
var connector = null;
if (parsed.url !== null) {
	connector = _.find(connectors, function(connector) {
		return _.find(connector.matches, function(patternStr) {
			var pattern = createPattern(patternStr);
			return pattern.test(parsed.url.href);
		});
	});
}
```
Or is there a reason to check Song.parsed.url inside the loop?

**Comment by alexesprit** [comment]
I fixed this issue by [this way](https://github.com/alexesprit/web-scrobbler/commit/693b524035d03207086beadfcc7c6b6a190b46b3). If it fits, I'll create a PR.
