### ISSUE TITLE
list of connectors?

### ISSUE THREAD

**Issue by ex47** [david-sabata/web-scrobbler#1023]
I feel like we need some structure. (list is not finished)

https://github.com/david-sabata/web-scrobbler/wiki/List-of-connectors

**Comment by alexesprit** [comment]
Is it better to place this list into [wiki](https://github.com/david-sabata/web-scrobbler/wiki)? So other people will be able to mark connectors as "working" instead of asking you to do that, for example.

**Comment by ex47** [comment]
It is. I though you need special rights to write there.

**Comment by ex47** [comment]
And why do we have not declared connectors?

**Comment by alexesprit** [comment]
Undeclared connector are v1 connectors that weren't be deleted after implementing them in v2 format. They can be safety removed.

**Comment by inverse** [comment]
Do we really need this?

**Comment by alexesprit** [comment]
I don't think we need it if this list will be always outdated.

Anyway, if someone wants to update the list, you can use [this gist](https://gist.github.com/alexesprit/65d6aed19ca677b6797898e7523a7bc0) as source of working connectors. All connectors marked as 'Works` are really works (checked 2-3 days ago).

**Comment by alexesprit** [comment]
I'm closing this because of following reasons:
1. Looks like no one is interesting in updating of the table.
2. v1 connectors are gone, so there's no sense to mark connectors as v1 and v2 in the table.
3. Connectors tests show the real status of connectors (but there is an exception for tests that checks only availability of web service).
