### ISSUE TITLE
Is it possible to inject into a web page, without using as a Chrome Extension?

### ISSUE THREAD

**Issue by aexmachina** [david-sabata/web-scrobbler#1062]
I'd like to use [Nativifier](https://github.com/jiahaog/nativefier) to create a Tidal app that includes this extension to scrobble to Last.fm. This provides a [`--inject`](https://github.com/jiahaog/nativefier/blob/development/docs/api.md#inject) option which I could use to inject this JavaScript, but it's not clear to me what the entry point is, or whether this package depends on Chrome extension infrastructure.

Is this possible? Where should I look to find an entry point for this package?

**Comment by alexesprit** [comment]
It's not enough just to inject some script into a page, because all hard work (scrobbling, playing state controlling etc) is done in background script. The communication between background script and connector/reactor (scripts are injected into a page) is implemented using Chome Messaging API. As you see it's all depends of Chrome API.

> Where should I look to find an entry point for this package?

The entry point is `core/background/main.js`.

**Comment by aexmachina** [comment]
Okay thanks.
