### ISSUE TITLE
Request: Force scrobble ambiguous entries

### ISSUE THREAD

**Issue by fdmsaraiva** [david-sabata/web-scrobbler#1066]
Not sure this is the place for a request but here goes.

While using the extension with Google Play Music, it very often happens that a new song starts playing but the scrobble notification doesn't come up.

When I go to the tab, the extension icon has a "?" instead of a checkmark, and I have to click it to manually submit the scrobble.

The thing is, the manual scrobble submission fields are always pre-filled with the correct values, so why weren't they submitted automatically?

I suppose they must be ambiguous in some way, but if what I end up doing anyway is manually submitting whatever was picked up, then I'd like the option to always force scroble allthethings and not have to manually submit dubious entries, because to me that only means a lot of scrobbles are being missed when I'm not at the computer or have the notification turned off.

**Comment by nershman** [comment]
I have a similar problem, I believe it is because some of the songs are not already in last.fm database. I think it would be good to enable force-scrobble on certain sites. For example on Plex I know my tags are correct so it shouldn't ever be ambiguous, but on youtube it should keep the question mark behavior.

**Comment by alexesprit** [comment]
@nershman This is already implemented, so what's your problem?
