### ISSUE TITLE
What do I do when my web scrobbler isn't scrobbling?

### ISSUE THREAD

**Issue by kyurawx1** [david-sabata/web-scrobbler#1225]
It shows it's scrobbling but it doesn't show in my profile, I used scrobbler last month and it was working, but I changed my last.fm account and I know I used to do something when I change my account but I don't remember what to do. Can someone help me?

**Comment by RadianM** [comment]
Have you tried re-authenticating your LastFM account? Click on the scrobbler icon top right of browser and select Options. Scroll all the way to the bottom of the page and click on the button labelled "Re-authenticate with Last.fm"

**Comment by alexesprit** [comment]
@kyurawx1 as @RadianM said before, you should reauthenticate via a button placed in the options page.

I also made a notification of service errors, so users will see a message when scrobbing isn't working due to authentication errors. This feature will be available in the next release. I hope it will help users to understand why the extension doesn't work properly.
