### ISSUE TITLE
spotify web player: no album name detected

### ISSUE THREAD

**Issue by usernameeeeeee** [david-sabata/web-scrobbler#1262]
When scrobbling from spotify in chrome web browser, the songtitle and the artist name get detected perfectly fine, except the album name never gets detected for any title.
Ofcourse, it can be written down manually in the empty third row, but doing this for every single song is pretty stressfull. Does anybody experience a similar problem or knows how to fix this?
Thanks!

**Comment by alexesprit** [comment]
Spotify doesn't show album title in the player bar, so I'm not sure it can be fixed.

**Comment by hans-juergen** [comment]
The web player shows the correct album cover though and if you hover the title or click on it, it will show the correctr album URL and/or switch to the correct album page. So it should possible, shouldn't it?

**Comment by alexesprit** [comment]
@hans-juergen The problem is the album should be fetched asynchronously, whereas artist and title are fetched synchronously. It's possible to do some hacks and get all track data asynchronously, like Gaana and Saavn connectors work, but I don't like this way.

I also thought about async base connector, but I have no idea how to implement it.
