### ISSUE TITLE
No way to access the menu in Firefox

### ISSUE THREAD

**Issue by darkalemanbr** [david-sabata/web-scrobbler#1289]
There's currently no way to access the extension's main menu/window in Firefox.

In Chrome this ability is provided by a button on the toolbox beside the omnibox and a similar option is expected in Firefox.

Another feasible option would be displaying a [page action](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction) only in tabs containing supported services.

**Comment by alexesprit** [comment]
The page action is already displayed, isn't it?

**Comment by darkalemanbr** [comment]
It isn't in my browser.

**Comment by alexesprit** [comment]
That's strange.
![image](https://cloud.githubusercontent.com/assets/1119267/25316985/0a378d60-2879-11e7-9ad6-61e78fc9a174.png)

The only thing I can say the page action becomes hidded when URL in address bar is changed in Firefox. The Opera doesn't do that, and Chrome didn't do too when the page action was shown in the omnibox. I don't know how to fix that on the extension side.

I also noticed it was fixed in some Firefox version, but Firefox developers changed the behaviour again.

**Comment by darkalemanbr** [comment]
After creating a new profile and loading just this extension I figured out I have another extension conflicting with page actions in general. So turns out this is happening in my end.

This isn't all for the bad, though, since I think I've found a potential flaw in another extension.

Closing.
