### ISSUE TITLE
Album info and autocorrection

### ISSUE THREAD

**Issue by alexesprit** [david-sabata/web-scrobbler#1321]
I tried to implement a feature suggested by @f1u77y in https://github.com/david-sabata/web-scrobbler/issues/1320#issuecomment-304694162 and found out the autocorrection flag affects on data received from Last.fm:
1. autocorrect=0: https://pastebin.mozilla.org/9023004
2. autocorrect =1: https://pastebin.mozilla.org/9023005

The second response looks more informative. That's true for some songs, for others Last.fm responses identically.

Should we remove this option and enable autocorrection? This action makes sense if the feature suggested in #1320 will be implemented.

**Comment by f1u77y** [comment]
If we don't want last.fm to perform autocorrect then it just send us back the data we've send, as I can understand. And this is right because fetching additional fields from last.fm is autocorrect too. So I think option to autofill album from last.fm should be either sub-option of autocorrect or be enabled if autocorrect is enabled (and don't be a separate option).

**Comment by alexesprit** [comment]
The option currently controls `autocorrect` flag value sent in `track.getinfo` request, but the responses are the same (I mean artist and track titles). At least, I have never seen the difference.

But the extension always corrects song data based on Last.fm response.
