### ISSUE TITLE
Firefox 54.0 Pandora (pandora.com) not working (version 1.66.0)

### ISSUE THREAD

**Issue by IRainman** [david-sabata/web-scrobbler#1347]
Firefox 54.0 Pandora (pandora.com) not working (version 1.66.0)

### Steps to Reproduce (for bugs)

1.  
2.  
3.  

### Steps for resolving the issue

- [x] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [x] Check other issues for duplicates

### Environment

* Version used: 1.66.0
* Browser Name and version: Firefox 54.0 

P.S. In there https://addons.mozilla.org/ru/firefox/addon/web-scrobbler/ version 1.66.0 is latest, no update available.

**Comment by f1u77y** [comment]
v1.67.1 is latest release. But AMO slows the update process a bit. The bug is fixed in 1.67 IIRC, so you need to install the extension from master if you need this right now.

(I'd like to distribute connectors separately because AMO (and maybe the Chrome Store) negates alexesprit's effort put into fast hotfixes of connectors)

**Comment by IRainman** [comment]
@f1u77y okay, thank u :)

P.S. Yeap, given the presence of slowpokes in AMO and possibly in the Chrome Store, I'm also for distributing connectors directly from the github.

**Comment by IRainman** [comment]
@f1u77y okay, thank u :)

P.S. Yeap, given the presence of slowpokes in AMO and possibly in the Chrome Store, I'm also for distributing connectors directly from the github.
