### ISSUE TITLE
Cannot scroble one song from YT

### ISSUE THREAD

**Issue by Draqun** [david-sabata/web-scrobbler#1349]
I have playlist, but there is one song and plugin does not scrobling it. This is link to song: https://www.youtube.com/watch?v=tnrQhaMb5u4&list=PLOR-Desu626gkXmURUlhacWLra_DM8nCR&index=16

### Expected Behavior
If song is not recognized I manually set title and artist

### Current Behavior
There is no action when this song is playing

### Possible Solution
Allow manully force scrobbling unrecognize song

### Steps to Reproduce (for bugs)
1. Go to https://www.youtube.com/watch?v=tnrQhaMb5u4&list=PLOR-Desu626gkXmURUlhacWLra_DM8nCR&index=16
2. Just watch it. 

### Environment
Chrome 50, Ubuntu Linux

**Comment by alexesprit** [comment]
1. This song is not in "Music" or "Entertainment" categories, and it cannot be scrobbled until these options are enabled:
![image](https://user-images.githubusercontent.com/1119267/27764703-b6238af6-5ea8-11e7-99ef-8c0158d20c11.png)
2. This song is now known by Last.fm, and user should manually submit the song data by clicking on "question" icon in the extension bar. There's an option called "Force song recognition" that makes the extension to accept unknown songs automatically.
![image](https://user-images.githubusercontent.com/1119267/27764709-090640ba-5ea9-11e7-9bff-06d65967ca72.png)

This behaviour is by design and won't be changed.

**Comment by Draqun** [comment]
Really fast answer. Ok now all is fine. Thx.

Best regards.

**Comment by f1u77y** [comment]
BTW option names are a bit misleading. Both disabled means scrobble all but it could be interpreted as "don't scrobble anything on YT"

**Comment by alexesprit** [comment]
@f1u77y yes, you're right. Earlier, there was a single option called "Scrobble videos from "Music" category **only**" that sounds better.

**Comment by f1u77y** [comment]
I suggest something like this
- [ ] Scrobble Music
- [ ] Scrobble Entertainment
- [ ] Scrobble everything else
