### ISSUE TITLE
Add support for freemusicarchive.org

### ISSUE THREAD

**Issue by inverse** [david-sabata/web-scrobbler#556]
Title says it all.

**Comment by Paszt** [comment]
I've got a connector created in my unpacked install as a version 2.  I'll fork and add it soon.

**Comment by inverse** [comment]
My advice would be to create a PR (Pull Request) for each connector. It might be a bit more work for your instance considering you've already got it all ready implemented. In which case perhaps having them all in a single PR might be okays. @david-sabata what do you think?

**Comment by david-sabata** [comment]
@Paszt please do make multiple PRs. It's the common workflow :-)

**Comment by Paszt** [comment]
I can make separate pull requests for each connector, no problem.

I was retesting the connector before adding and I've found an odd bug.  On most pages at freemusicarchive.org, there are multiple "playlist" areas, so I'm observing nearly the whole page.  The bug is that track.getinfo is being sent if there is a valid artist but the track is an empty string, and vice versa, and even if isPlaying returns false. I tried to work around it by setting artist and track to null if it's not playing, but that messes with the pause functionality. I would have thought requests would't be sent if either track or artist is an empty string.  I haven't looked too heavily into the V2 core code though.

**Comment by inverse** [comment]
@Paszt  any progress on this?

**Comment by Paszt** [comment]
I thought maybe the latest changes to controller.js to "fix isPlaying flag for newly detected track" might have fixed the issue, but it's still occurring.  I have issued a PR with the freemusicarchive.org connector.  The issue can be reproduced by going to http://freemusicarchive.org/music/My_Monthly_Date/Miles_Away_EP/

![image](https://cloud.githubusercontent.com/assets/1742693/7039752/18c210b2-dd94-11e4-8424-09f4d850d7c7.png)

As you can see, a getInfo request is sent even though isPlaying is false and track is null.

**Comment by david-sabata** [comment]
@Paszt you're right that when artist or track is `null`, no request should be sent and we should short-circuit to unrecognized track
