### ISSUE TITLE
Display album cover in notification

### ISSUE THREAD

**Issue by AltarBeastiful** [david-sabata/web-scrobbler#580]
We could get the album cover from the music service and display it in the notification. It could even be retrieved from last.fm once it's scrobbled, if it's unavailable on the service page.

A similar proposition was made in #180.

**Comment by inverse** [comment]
It's already available in the `v2` connectors.

**Comment by AltarBeastiful** [comment]
Great to see! I'll get to porting the ones I use intensively then.

Is there anything blocking, known difficulties, for porting SoundCloud and Bandcamp to v2 ?

**Comment by inverse** [comment]
Both of these connectors are written differently. For example the SC one binds to the command bus of the website. Whereas the BC connector listens to events triggered by the `audio` player on the page.

The `v2` connectors are built such that they watch a DOM element for changes. i.e. when a track plays etc. Whilst this solution could work for both I feel that perhaps the `v2` connectors mechanism should be extended to respond to events (from custom players) rather than DOM updates. Perhaps using some adaptor pattern.

**Comment by Paszt** [comment]
The v2 connectors don't have to watch for DOM changes.  It's possible to explicitly invoke Connector.onStateChanged in response to some other event.  

I've created a v2 BandCamp connector, PR #584, that binds the audio element events.  I'm not really sure what the advantage is of using the audio element events over DOM changes, but it's pretty simple so I've opted to use the audio events.

**Comment by inverse** [comment]
@Paszt Thanks for that PR! I wasn't sure how to hook up the v2 scrobbler mechanism to the audio tag eventing system.

Isn't the a performance gain for only being 'updating' when actual events occur instead of binding to dom updates to the player?

**Comment by Paszt** [comment]
In the case of the BandCamp connector, I'm binding to the playing, pause, & timeupdate events.  So it's updating every second. Using DOM updates or audio events will be the same amount of updates. One update every second shouldn't be too taxing.

I chose to include timeupdate so that currentTime is updated.  There's logic in the [controller](https://github.com/david-sabata/web-scrobbler/blob/master/core/background/controller.js#L69) that allows songs to be scrobbled again if played multiple times (isNewStateNearStart, isReplayingSong). See issues #535 & #230.

**Comment by inverse** [comment]
That's cool, and makes sense. In the previous iteration when the song had finished playing reset was triggered. I'm guessing this `timeupdate` event hook allows for that with those two states you mentioned.

**Comment by Paszt** [comment]
After further testing, I've found that DOM mutations and audio events happen at about the same rate, on my setup anyway (a DOM mutation or audio event every 250ms, approximately).  So it seems it doesn't make any difference. Here's the code I use to test the rate:

```javascript
// DOM mutation timer, as used in /core/content/starter.js 
var observer = new MutationObserver(function(mutations) {
    console.timeEnd("mutation");
    console.time("mutation");
});
var observeTarget = document.querySelector('div.inline_player');
var config = {
    childList: true,
    subtree: true,
    attributes: true,
    characterData: true
};
observer.observe(observeTarget, config);

// audio events timer
$('audio').first().bind('playing pause timeupdate', function() {
    console.timeEnd("audio event");
    console.time("audio event");
});
```

It doesn't seem that a reset is necessary with the v2 connectors, though I'm not exactly sure.

And yeah, the `timeupdate` event hook allows for repeated songs to be scrobbled multiple times.

**Comment by inverse** [comment]
@Paszt  thanks for conducing this evaluation and sharing your test code!
