### ISSUE TITLE
When currently scrobbling, clicking on the icon no longer works

### ISSUE THREAD

**Issue by EnviousElitist** [david-sabata/web-scrobbler#638]
Clicking on the icon while it is green and scrobbling no longer allows controlling the scrobbling (e.g. turning off and on).  It works before the icon turns green (music is currently playing and being scrobbled).  

tested on:
play.spotify.com
Ubuntu 14.04
Chrome 43.0.2357.81 64-bit

**Comment by inverse** [comment]
I remember this feature. Looking through the code perhaps this wasn't ported when refactoring the code base to use AMD. I can see there is an onClick function that perhaps it's just there that it needs to be wired up.

**Comment by david-sabata** [comment]
True. I removed (or intentionally skipped) this feature when implementing `v2` so this issue is relevant for all `v2` connectors.

It's because I have long-term idea for a little window that would show upon clicking the icon, whatever state it is currently in. The scrobbling should be paused using a button in notification instead, which too is not implemented yet.

**Comment by janbaykara** [comment]
Something discussed in #616 - disable/enable scrobbling via popup.

**Comment by alexesprit** [comment]
Now the extension allows to disable connectors via page action context menu.
