### ISSUE TITLE
Amazon Cloud Scrobbling is Broken

### ISSUE THREAD

**Issue by irokie** [david-sabata/web-scrobbler#646]
Listening on https://www.amazon.com/gp/dmusic/cloudplayer/player?ie=UTF8&ref_=nav_youraccount_cldplyr#playList/name=New+Choons/list=9b2b4564-cc62-4370-ba80-ba679f06b5b5 in Chrome Version 43.0.2357.124 m on Windows 7.

Behaviour:  I see the red "AS" logo, and the plug-in does not recognise that music is currently playing.  

Troubleshooting:  I've tried a couple of things that usually prevent the plugin from scrobbling:
1. Ensured that the current playlist has focus
2. Ensured that the playlist is not too long
3. Ensured that the currently playing track is also on-screen.

Please let me know if there's any additional data that I can prove.

Thanks!

**Comment by Paszt** [comment]
There are instruction here that you could follow to get more data: /wiki/How-to-debug-the-extension 

I can't test your playlist, but it worked for one of mine just now.  Thanks.

**Comment by brarig219** [comment]
I'm not overly well versed in coding, so forgive me if this isn't what you were asking for.  I'm having the same issue.  Music is playing through Amazon's Cloud player via Chrome, and while I have the red box in the top left corner, it won't turn green with the checkmark liked it used to, which indicates scrobbling. 

Here is the info from Paszt's link on How To Debug The Extension:

chrome.storage.local = {"Core":{"appVersion":"1.49"},"LastFM":{"sessionID":"xxxxx759246a5d5e0c9ec7aa24abe209","token":null}}
main.js:213 LastFM: Session ID xxxxx759246a5d5e0c9ec7aa24abe209
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-2.1.0.min.js
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-2.1.0.min.js
2inject.js:107 	injecting vendor/underscore-min.js
2inject.js:107 	injecting core/content/reactor.js
2inject.js:107 	injecting core/content/connector.js
2inject.js:107 	injecting connectors/v2/amazon.js
2inject.js:107 	injecting core/content/starter.js
2controller.js:311 Tab 8: created controller for connector: {"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*"],"js":["connectors/v2/amazon.js"],"version":2}
2inject.js:120 -- subsequent ajax navigation, the scripts are already injected
controller.js:92 Tab 8: new track state: {"track":"Drunks, Lovers, Sinners And Saints","artist":"Alexisonfire","album":"Crisis","uniqueID":"1ffc67e9-0cd1-488f-8836-87992e7f3bcc","duration":228,"currentTime":0,"isPlaying":false,"trackArt":null}
controller.js:100 Tab 8: new song detected: {"parsed":{"artist":"Alexisonfire","track":"Drunks, Lovers, Sinners And Saints","album":"Crisis","uniqueID":"1ffc67e9-0cd1-488f-8836-87992e7f3bcc","duration":228,"currentTime":null,"isPlaying":false,"trackArt":false},"processed":{"artist":"Alexisonfire","track":"Drunks, Lovers, Sinners And Saints","album":"Crisis","duration":228},"metadata":{"startTimestamp":1436892850},"flags":{"isProcessed":false,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":null,"isMarkedAsPlaying":false}}
controller.js:82 Tab 8: state update: {"track":"Drunks, Lovers, Sinners And Saints","artist":"Alexisonfire","album":"Crisis","uniqueID":"1ffc67e9-0cd1-488f-8836-87992e7f3bcc","duration":228,"currentTime":0,"isPlaying":true,"trackArt":null}
controller.js:128 Tab 8: isPlaying state changed to true
32controller.js:80 Tab 8: state update: only currentTime has changed
lastfm.js:208 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.getinfo&autocorrect=0&artis…overs%2C%20Sinners%20And%20Saints&api_key=d9bb1870d3269646f740544d9def2c95 : success
<?xml version="1.0" encoding="utf-8"?><lfm status="ok">
<track>
    <id>61160179</id>
    <name>Drunks, Lovers, Sinners and Saints</name>
            <mbid>59ae218d-4467-4663-a088-409a879a721e</mbid>
            <url>http://www.last.fm/music/Alexisonfire/_/Drunks,+Lovers,+Sinners+and+Saints</url>
    <duration>229000</duration>
    <streamable fulltrack="0">0</streamable>    
        <listeners>127504</listeners>
    <playcount>1134337</playcount>
        <artist>
        <name>Alexisonfire</name>
                <mbid>bc1c8f3f-6f36-4086-a470-87ed813dd429</mbid>
                    <url>http://www.last.fm/music/Alexisonfire</url>
    </artist>
        <album position="1">
        <artist>Alexisonfire</artist>
        <title>Crisis</title>
                <mbid>57881c5a-f4f7-4f1a-8963-f339101f747f</mbid>
                    <url>http://www.last.fm/music/Alexisonfire/Crisis</url>        
        <image size="small">http://userserve-ak.last.fm/serve/64s/95102443.png</image>
        <image size="medium">http://userserve-ak.last.fm/serve/126/95102443.png</image>
        <image size="large">http://userserve-ak.last.fm/serve/174s/95102443.png</image>
        <image size="extralarge">http://userserve-ak.last.fm/serve/300x300/95102443.png</image>
    </album>
        <toptags>
        <tag>
	  <name>post-hardcore</name>
	  <url>http://www.last.fm/tag/post-hardcore</url>
	</tag>
        <tag>
	  <name>screamo</name>
	  <url>http://www.last.fm/tag/screamo</url>
	</tag>
        <tag>
	  <name>hardcore</name>
	  <url>http://www.last.fm/tag/hardcore</url>
	</tag>
        <tag>
	  <name>emocore</name>
	  <url>http://www.last.fm/tag/emocore</url>
	</tag>
        <tag>
	  <name>rock</name>
	  <url>http://www.last.fm/tag/rock</url>
	</tag>
      </toptags>
    </track></lfm>
musicbrainz-coverartarchive.js:13 Found album artwork via LastFM
controller.js:148 Tab 8: song finished processing  {"parsed":{"artist":"Alexisonfire","track":"Drunks, Lovers, Sinners And Saints","album":"Crisis","uniqueID":"1ffc67e9-0cd1-488f-8836-87992e7f3bcc","duration":228,"currentTime":32,"isPlaying":true,"trackArt":false},"processed":{"artist":"Alexisonfire","track":"Drunks, Lovers, Sinners and Saints","album":"Crisis","duration":229},"metadata":{"startTimestamp":1436892850,"artistThumbUrl":"http://userserve-ak.last.fm/serve/126/95102443.png"},"flags":{"isProcessed":true,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":true,"isMarkedAsPlaying":false}}
controller.js:198 Tab 8: the song will be scrobbled after 81.5 more seconds of playback
controller.js:80 Tab 8: state update: only currentTime has changed
lastfm.js:208 L.FM response to https://ws.audioscrobbler.com/2.0/?method=track.updatenowplaying&track=Drun…=24f53759246a5d5e0c9ec7aa24abe209&api_sig=62c16af9f47b98ca784af8f911976d37 : success
<?xml version="1.0" encoding="utf-8"?><lfm status="ok">
<nowplaying>
    <track corrected="0">Drunks, Lovers, Sinners and Saints</track>
    <artist corrected="0">Alexisonfire</artist>
    <album corrected="0"/>
    <albumArtist corrected="0"/>
    <ignoredMessage code="0"/>
</nowplaying></lfm>
controller.js:230 Tab 8: song set as now playing: true
34controller.js:80 Tab 8: state update: only currentTime has changed
controller.js:82 Tab 8: state update: {"track":"Drunks, Lovers, Sinners And Saints","artist":"Alexisonfire","album":"Crisis","uniqueID":"1ffc67e9-0cd1-488f-8836-87992e7f3bcc","duration":228,"currentTime":67,"isPlaying":false,"trackArt":null}
controller.js:128 Tab 8: isPlaying state changed to false

**Comment by pjbingham** [comment]
+1

I still have this problem, despite - I believe - a release that's been made to address it (#838).

I'm now on Chrome 49.0.2623.0 canary (64-bit).

Following the how-to-debug instructions...

It seems to be finding the right connector (which would be consistent with it recognising the site, as it does):

Tab 770: created controller for connector: {"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*"],"js":["connectors/v2/amazon.js"],"version":2}

Here's the rest - it seems to be failing with authentication to last.fm?

Tab 770: new track state: {"track":"Love Burns","artist":"Black Rebel Motorcycle Club","album":"FABRICLIVE 16: Adam Freeland","uniqueID":null,"duration":null,"currentTime":0,"isPlaying":true,"url":{"hash":"#albumDetail/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","search":"?ie=UTF8&ref_=nav_gno_yam_cldplyr","pathname":"/gp/dmusic/cloudplayer/player","port":"","hostname":"www.amazon.co.uk","host":"www.amazon.co.uk","protocol":"https:","origin":"https://www.amazon.co.uk","href":"https://www.amazon.co.uk/gp/dmusic/cloudplayer/player?ie=UTF8&ref_=nav_gno_…l/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","ancestorOrigins":{}},"trackArt":"https://album-art-storage-eu.s3.amazonaws.com/22e5877b2033b3ad937c72b4a718f…FY2FQH3QBTIQ&Expires=1453326700&Signature=D7lqX%2B7WjDpaBqWXT9FJPyqYAbM%3D"}
controller.js:100 Tab 770: new song detected: {"parsed":{"artist":"Black Rebel Motorcycle Club","track":"Love Burns","album":"FABRICLIVE 16: Adam Freeland","uniqueID":null,"duration":null,"currentTime":null,"isPlaying":true,"trackArt":"https://album-art-storage-eu.s3.amazonaws.com/22e5877b2033b3ad937c72b4a718f…FY2FQH3QBTIQ&Expires=1453326700&Signature=D7lqX%2B7WjDpaBqWXT9FJPyqYAbM%3D","url":{"hash":"#albumDetail/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","search":"?ie=UTF8&ref_=nav_gno_yam_cldplyr","pathname":"/gp/dmusic/cloudplayer/player","port":"","hostname":"www.amazon.co.uk","host":"www.amazon.co.uk","protocol":"https:","origin":"https://www.amazon.co.uk","href":"https://www.amazon.co.uk/gp/dmusic/cloudplayer/player?ie=UTF8&ref_=nav_gno_…l/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","ancestorOrigins":{}}},"processed":{"artist":"Black Rebel Motorcycle Club","track":"Love Burns","album":"FABRICLIVE 16: Adam Freeland","duration":null},"metadata":{"userloved":false,"startTimestamp":1453240386,"url":{"hash":"#albumDetail/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","search":"?ie=UTF8&ref_=nav_gno_yam_cldplyr","pathname":"/gp/dmusic/cloudplayer/player","port":"","hostname":"www.amazon.co.uk","host":"www.amazon.co.uk","protocol":"https:","origin":"https://www.amazon.co.uk","href":"https://www.amazon.co.uk/gp/dmusic/cloudplayer/player?ie=UTF8&ref_=nav_gno_…l/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","ancestorOrigins":{}},"connector":{"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*"],"js":["connectors/v2/amazon.js"],"version":2}},"flags":{"isProcessed":false,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":null,"isMarkedAsPlaying":false}}
jquery-2.1.0.min.js:4 GET https://ws.audioscrobbler.com/2.0/?method=auth.getsession&api_key=d9bb1870d…c7275b0791325333cf3e7&api_sig=e8df954c1ce18f0034ef6cf2d95cd9a3&format=json 403 (Forbidden)l.cors.a.crossDomain.send @ jquery-2.1.0.min.js:4o.extend.ajax @ jquery-2.1.0.min.js:4o.(anonymous function) @ jquery-2.1.0.min.js:4o.extend.getJSON @ jquery-2.1.0.min.js:4tradeTokenForSession @ lastfm.js:135(anonymous function) @ lastfm.js:91(anonymous function) @ chromeStorage.js:26target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
lastfm.js:145 auth.getSession failed: Forbidden, error(anonymous function) @ lastfm.js:145j @ jquery-2.1.0.min.js:2k.fireWith @ jquery-2.1.0.min.js:2x @ jquery-2.1.0.min.js:4(anonymous function) @ jquery-2.1.0.min.js:4
controller.js:92 Tab 770: new track state: {"track":"Love Burns","artist":"Black Rebel Motorcycle Club","album":"FABRICLIVE 16: Adam Freeland","uniqueID":"c3f7c136-d2c2-4173-b681-74445e06562f","duration":136,"currentTime":0,"isPlaying":true,"url":{"hash":"#albumDetail/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","search":"?ie=UTF8&ref_=nav_gno_yam_cldplyr","pathname":"/gp/dmusic/cloudplayer/player","port":"","hostname":"www.amazon.co.uk","host":"www.amazon.co.uk","protocol":"https:","origin":"https://www.amazon.co.uk","href":"https://www.amazon.co.uk/gp/dmusic/cloudplayer/player?ie=UTF8&ref_=nav_gno_…l/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","ancestorOrigins":{}},"trackArt":"https://album-art-storage-eu.s3.amazonaws.com/22e5877b2033b3ad937c72b4a718f…FY2FQH3QBTIQ&Expires=1453326700&Signature=D7lqX%2B7WjDpaBqWXT9FJPyqYAbM%3D"}
controller.js:100 Tab 770: new song detected: {"parsed":{"artist":"Black Rebel Motorcycle Club","track":"Love Burns","album":"FABRICLIVE 16: Adam Freeland","uniqueID":"c3f7c136-d2c2-4173-b681-74445e06562f","duration":136,"currentTime":null,"isPlaying":true,"trackArt":"https://album-art-storage-eu.s3.amazonaws.com/22e5877b2033b3ad937c72b4a718f…FY2FQH3QBTIQ&Expires=1453326700&Signature=D7lqX%2B7WjDpaBqWXT9FJPyqYAbM%3D","url":{"hash":"#albumDetail/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","search":"?ie=UTF8&ref_=nav_gno_yam_cldplyr","pathname":"/gp/dmusic/cloudplayer/player","port":"","hostname":"www.amazon.co.uk","host":"www.amazon.co.uk","protocol":"https:","origin":"https://www.amazon.co.uk","href":"https://www.amazon.co.uk/gp/dmusic/cloudplayer/player?ie=UTF8&ref_=nav_gno_…l/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","ancestorOrigins":{}}},"processed":{"artist":"Black Rebel Motorcycle Club","track":"Love Burns","album":"FABRICLIVE 16: Adam Freeland","duration":136},"metadata":{"userloved":false,"startTimestamp":1453240388,"url":{"hash":"#albumDetail/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","search":"?ie=UTF8&ref_=nav_gno_yam_cldplyr","pathname":"/gp/dmusic/cloudplayer/player","port":"","hostname":"www.amazon.co.uk","host":"www.amazon.co.uk","protocol":"https:","origin":"https://www.amazon.co.uk","href":"https://www.amazon.co.uk/gp/dmusic/cloudplayer/player?ie=UTF8&ref_=nav_gno_…l/FABRICLIVE+16%3A+Adam+Freeland/FABRICLIVE+16+ADAM+FREELAND/ADAM+FREELAND","ancestorOrigins":{}},"connector":{"label":"Amazon","matches":["*://www.amazon.com/gp/dmusic/cloudplayer/*","*://www.amazon.de/gp/dmusic/cloudplayer/*","*://www.amazon.es/gp/dmusic/cloudplayer/*","*://www.amazon.co.uk/gp/dmusic/cloudplayer/*"],"js":["connectors/v2/amazon.js"],"version":2}},"flags":{"isProcessed":false,"isScrobbled":false,"isCorrectedByUser":false,"isLastfmValid":null,"isMarkedAsPlaying":false}}
jquery-2.1.0.min.js:4 GET https://ws.audioscrobbler.com/2.0/?method=auth.getsession&api_key=d9bb1870d…c7275b0791325333cf3e7&api_sig=e8df954c1ce18f0034ef6cf2d95cd9a3&format=json 403 (Forbidden)l.cors.a.crossDomain.send @ jquery-2.1.0.min.js:4o.extend.ajax @ jquery-2.1.0.min.js:4o.(anonymous function) @ jquery-2.1.0.min.js:4o.extend.getJSON @ jquery-2.1.0.min.js:4tradeTokenForSession @ lastfm.js:135(anonymous function) @ lastfm.js:91(anonymous function) @ chromeStorage.js:26target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
lastfm.js:145 auth.getSession failed: Forbidden, error(anonymous function) @ lastfm.js:145j @ jquery-2.1.0.min.js:2k.fireWith @ jquery-2.1.0.min.js:2x @ jquery-2.1.0.min.js:4(anonymous function) @ jquery-2.1.0.min.js:4
60controller.js:80 Tab 770: state update: only currentTime has changed

What's weird as I've literally only just authenticated with last.fm and got the confirmation that it was successful.

Somewhere along the line the plugin HAS now started reporting that it's looking up tracks - it wasn't doing this when I reported #821, nor the first few times I tried it in these tests.  Don't know what might have caused it to start attempting to look tracks up... but it still isn't actually scrobbling them (presumably due to the authentication failure).

Hope this helps with tracking this one down.  Please do get in touch if I can help with further information, etc.

I believe I'm on version 1.56 of the extension by the way.

**Comment by MartinL0815** [comment]
May be this is worth a new issue … in Google Chrome Version 49.0.2623.87 on Amazon Music Library the scrobbler icon in the address bar is NOT drawn, so there is no control whether it is working or not.

**Comment by LaHaine** [comment]
It doesn't work for me on Amazon music for PRIME, e.g. https://music.amazon.de/albums/B009YA7IZ2/PRIME/
The 'as' icon stays grey. Scrobbling from other sources like Youtube is working fine.

**Comment by Wenger786** [comment]
I have the same issue: Scrobbling of amazon (Prime) music not scrobbling using the web-payer (https://music.amazon.co.uk) - actually it seems https://music.amazon.co.uk/recommended is okay, and scrobbled, but https://music.amazon.co.uk/home?do=play&playlistAsin=B012GC0ENW is not.  Last.fm Scrobbler 1.59 turns red for both URL's but only scrobbles the former (with the expected "now playing"  and "scrobbled" notifications/icons. the latter remains saying "Play some music to get started", even though music is played.

**Comment by alexesprit** [comment]
Closed as outdated.
