### ISSUE TITLE
Google Music no longer scrobbling.

### ISSUE THREAD

**Issue by kmehlin** [david-sabata/web-scrobbler#682]
It looks like something changed? I'm not sure what, but the scrobbling is not working.

**Comment by Paszt** [comment]
It works for me, though I am seeing some huge delays from last.fm, sometimes longer than a minute for a response.

**Comment by kmehlin** [comment]
Seems to be working now, yes. I think it is on Last.fm's end. Thank you for the verification.

**Comment by ajft** [comment]
On and off over the past few days, sometimes it'll scrobble, other times it won't. My google accounts were all logged out yesterday and after logging back in it's consistent -- no scrobbling through google music.

**Comment by dgw** [comment]
Not scrobbling Google Music here either.

**Comment by david-sabata** [comment]
L.FM was migrating to new website in past days, so that's maybe where those delays and outages came from.

I'm scrobbling just fine from Google Music now. Can you confirm? Also if the problem perists please [post some console info](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by dgw** [comment]
Appears to be working once again for me, as well. The extension has resumed showing notifications when I start playing something (previously it did not detect playback) so perhaps this is resolved—or what I was experiencing is unrelated.

**Comment by david-sabata** [comment]
Ok, I'll close this. Feel free to reopen if you get any more info on this
