### ISSUE TITLE
don't work anymore with the new last.fm website

### ISSUE THREAD

**Issue by pateretou** [david-sabata/web-scrobbler#698]
it seems since the last.fm website update the extension doesn't work anymore (version 1.50)

**Comment by bes-internal** [comment]
Hello,

We’re going live with our new site today. Due to this, some functionality may be temporarily unavailable. Below, we’ve listed the areas that may experience some disruption.
https://getsatisfaction.com/lastfm/topics/new-site-launch-temporary-service-disruption-information
Many Thanks,
Team Last.fm
Posted about 2 days ago by http://status.last.fm/

<img src=http://internal.by/i/screen_20150819-162623.png>

**Comment by david-sabata** [comment]
Should be resolved in the next release by #701
