### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by Andead** [david-sabata/web-scrobbler#765]
Trying to re-authenticate scrobbler, getting "ERR_CONNECTION_TIMED_OUT".

**Comment by galeksandrp** [comment]
Look like last.fm blocked in our Russia. Note that your ISP need to block only separate pages of last.fm, not full site. For now only one page is blocked. Send an abuse to your ISP.

For future cases, check [there](http://reestr.rublacklist.net/search/?q=last.fm) or [there](https://antizapret.info/index.php?search=last.fm). If you see a url starting with `https://`, it means that full site will be blocked.

**Comment by david-sabata** [comment]
Not much we can do -_-

**Comment by Andead** [comment]
Wait, but i still can access the whole last.fm site, use my desktop scrobbler app. And the blocked pages list does not contain anything but one "Психея" song, it's not the url my browser is trying to open when re-authenticating.

**Comment by david-sabata** [comment]
And what's the url that you're getting timeouts on?

Connection timeout is almost always caused by network issues. It can be you, it can be your provider or even the L.FM. But lots of people would be reporting this if it was a global issue.

**Comment by galeksandrp** [comment]
@david-sabata url is `https://www.last.fm/api/auth/?api_key=d9bb1870d3269646f740544d9def2c95&token=...`. Note `https://`. @Andead have https on lastfm fully blocked, because https does not allow url recoginizing for ISP proxy. Because last.fm does not use https even for `/api/auth` endpoint (it redirects from https to http), protocol in extension should be switched to http.

**Comment by Andead** [comment]
Yes, thank you. Changing protocol to http helped. Don't wanna mess with them ISP's, though.
