### ISSUE TITLE
Extension does not work at all

### ISSUE THREAD

**Issue by poetlee** [david-sabata/web-scrobbler#796]
Hi, I'm using macbook and I just installed the extension today.
When I am on youtube or soundcloud, I see an icon saying 'this site is supported for scrobbling'.
But it doesn't recognise any songs at all on both sites.
Even if I play a song, the icon stays the same.
I do not know what is wrong with it :(

**Comment by inverse** [comment]
Got some sample URLs that are highlighting the problem?

**Comment by poetlee** [comment]
Well, actually no songs are detected so any URL would be a sample.
Here are some of songs that I've tried
https://www.youtube.com/watch?v=OJ-FsBvz4i8
https://www.youtube.com/watch?v=Xi1_GYahCSs
https://soundcloud.com/fkj-2/fkj-lying-together

**Comment by fedorg** [comment]
First of all, please make sure that all connectors are enabled in the extension options, then reconnect your last.fm with "re-authenticate with last.fm" button at the bottom of the list, and after you've done that, reload the extension. If that doesn't help, then there might be several things at play including network issues, and you can help find the root cause by providing logs. There are two types of them: page logs can be viewed by pressing Cmd + Opt + I; getting to background logs is harder, but it's nicely explained [here](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension).
If the extension does not work at all, this is usually an authentication problem. If it does work for any other sites, for example Bandcamp, this is probably a bug.

**Comment by poetlee** [comment]
Thanks for your reply!
When I check background logs, it has two red line errors.
![image](https://cloud.githubusercontent.com/assets/14824281/10112335/b553bb3c-641d-11e5-8ba6-0ec9c7307351.png)

with
{"error":4,"message":"Invalid authentication token supplied"}

**Comment by Paszt** [comment]
@poetlee, Did you do this part:  "make sure that all connectors are enabled in the extension options, then reconnect your last.fm by pressing the "re-authenticate with last.fm" button at the bottom of the list"?

**Comment by poetlee** [comment]
Do you mean this one?
![image](https://cloud.githubusercontent.com/assets/14824281/10116417/0b825f68-6478-11e5-8710-764fb3665192.png)
It's been enabled the whole time.
If you guys mean something other than that, could you tell me where to find it?

**Comment by poetlee** [comment]
![image](https://cloud.githubusercontent.com/assets/14824281/10116453/33676aea-6479-11e5-8050-4112ca1b1b92.png)
And this is page log

**Comment by fedorg** [comment]
![how_to_reauth](https://cloud.githubusercontent.com/assets/4352852/10118558/a73e2cba-6483-11e5-9d35-d16d0af7876c.png)

**Comment by fedorg** [comment]
We should probably do a reauth automatically after receiving an invalid token error. At least, the notification should show up every time this happens.

**Comment by poetlee** [comment]
It works now. Thank you so much!
