### ISSUE TITLE
Google Play Music Not Scrobbling

### ISSUE THREAD

**Issue by sierratango88** [david-sabata/web-scrobbler#807]
I have tried restarting Chrome, the extension, and reauthenticating but I keep getting a bad request with Last.fm and Google Play Music according to Chrome's console:
![error](https://cloud.githubusercontent.com/assets/15116177/10472287/c5a3a470-71ec-11e5-991a-34995e33d555.png)

Not sure if this is a problem with Last.fm's end or the extension.

**Comment by TheQwerty** [comment]
This looks like what happens when Last.fm is not familiar with the track.

The requested URL is presumably:
https://ws.audioscrobbler.com/2.0/?method=track.getinfo&autocorrect=0&username=undefined&artist=Christopher%20Haigh&track=Strength%20To%20Overcome&api_key=d9bb1870d3269646f740544d9def2c95

Which actually does work and returns the following even though Last.fm also returns a 400 status code:
```
<lfm status="failed">
<error code="6">Track not found</error>
</lfm>
```

Making the same request from Last.fm but using the JSON format instead:
https://ws.audioscrobbler.com/2.0/?method=track.getinfo&autocorrect=0&username=undefined&artist=Christopher%20Haigh&track=Strength%20To%20Overcome&api_key=d9bb1870d3269646f740544d9def2c95&format=json
Returns a 200 and the following:
```
{"error":6,"message":"Track not found","links":[]}
```

During that song the address bar should display a gray icon with white question mark. You can click this to manually scrobble the song, but it's pretty annoying if you're listening to a lot of music not yet found on Last.fm.

This is also discussed in issue #452.

**Comment by sierratango88** [comment]
Ah ok I understand what's going on now. Thanks for the clarification and looking into this issue. Hopefully David can help us out here.

**Comment by david-sabata** [comment]
@sierratango88 these requests are ok, just as @TheQwerty said. They're just failed track lookups.

When you click the address bar icon (which should be gray with question mark), fix the track info and submit, it will be added to L.FM and correctly scrobbled. Next time the track should be recognized just fine.

Feel free to reply for more info. I'll close this as not-a-bug :)

**Comment by sierratango88** [comment]
Hi David,

Thank you for your response and suggestion.

I would like to do as you said to fix/submit certain unknown tracks but since I listen to Google Music from Chrome's window mode, there is no address bar and therefore I cannot click on your extension button. Can I suggest that you add a Chrome keyboard shortcut key to be able to activate your extension from any window?

Thanks for all your hard work.
