### ISSUE TITLE
A wiki page on raising an issue

### ISSUE THREAD

**Issue by inverse** [david-sabata/web-scrobbler#816]
We often get people raising issues without providing enough information. I propose a new page in the wiki on how the information we need. 

I don't mind picking this up at some point... unless someone else wants to make a start!

**Comment by alexesprit** [comment]
Github has a [feature](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) to show link to contribution guidelines on creating issues/PRs. So all instructions to get information we need can be placed into this file instead of wiki. I also created [an example of this file](https://gist.github.com/alexesprit/4b966cb89f231a040c8fa228bf1e138b.pibb) which, of course, can be used as a default one.

**Comment by f1u77y** [comment]
We can make an issue template. Some people don't check the wiki before repoting the issue but they will see the issue template. So I think it's better option to provide it insted of wiki page.

**Comment by alexesprit** [comment]
An [example][1] of issue template generated by [this service][2]. 

Is there something that should be mentioned in the template?

[1]: https://gist.githubusercontent.com/alexesprit/c280c6b92b896fce70eba5a21fa37207/raw/92d89bc332e39e34ec274f2ec00dc5033db562dd/ISSUE_TEMPLATE.md
[2]: https://www.talater.com/open-source-templates/#/

**Comment by f1u77y** [comment]
> * Operating System and version:

Isn't it useless?

It would be nice to add common steps for resolving the issue. I'd like to suggest these ones:
- [ ] Reauth on last.fm(if it does not scrobble at all)
- [ ] Try to use unpacked extension from latest master
- [ ] Check other issues for dups

**Comment by alexesprit** [comment]
@f1u77y 

> Isn't it useless?

I don't really know. Well, I'll remove that section; it can be easily added if we'll need this kind of information sometimes later or just ask users for it in issue comments.

> It would be nice to add common steps for resolving the issue.

That's a good idea! The "Try to use unpacked extension from latest master" step should be extended by placing URL to page with "Install as unpacked extension" howto, though.

I updated [the template][1] according your suggestion and added some comments to that steps.

The only one thing I don't like is that this template is mostly for bugs, not for suggestions.The user should remove almost all template text, if they want to just suggest a new feature or request a support for new web service.

[1]: https://gist.githubusercontent.com/alexesprit/c280c6b92b896fce70eba5a21fa37207/raw/546b033fa67c80bdb2189f714215e50e3e8cd45b/ISSUE_TEMPLATE.md

**Comment by f1u77y** [comment]
> I don't really know. Well, I'll remove that section; it can be easily added if we'll need this kind of information sometimes later or just ask users for it in issue comments.

WebExtensions are designed to work identically on all browsers and OSes(OK, at least on Chromium(-based)). If they don't, that's a browser bug, or maybe, some other extension(eg. one of uBlock lists contains ws.audioscrobbler.com for some reason). But I think that's rare cases, so yes, we can ask about OS/other extensions only if it seems to be not our bug.

> The only one thing I don't like is that this template is mostly for bugs, not for suggestions.The user should remove almost all template text, if they want to just suggest a new feature or request a support for new web service.

That's GH limitations. Ideally, there should be separate templates for feature requests and bug reports.

> I updated the template according your suggestion and added some comments to that steps.

I have no other suggestions.

**Comment by alexesprit** [comment]
> I have no other suggestions.

Could you please also check the contribution guide (see my first comment in this thread)? This guide is designed for developers who want co contribute by proposing PRs, but it also contains information about submitting issues, that possibly duplicates information placed in the issue template. So, I have two questions:
1. Shoud the information for developers be extended? If so, what should be added/changed/removed?
2. Shoud the information about posting bugs be removed? Instead of this, we could mention that we have a issue template where all needed information is available.

**Comment by f1u77y** [comment]
> Shoud the information for developers be extended? If so, what should be added/changed/removed?

I think info about editorconfig should be added. Some devs can miss .editorconfig in the repo(especially if they didn't know about it before).

Another point is about connector development. I dunno if it does not contains enough info or people just don't read it properly but I see your points about simplifying connectors in many pull requests. That makes me sure that we need to add some common advices about connector development.

> Shoud the information about posting bugs be removed? Instead of this, we could mention that we have a issue template where all needed information is available.

> If you don't know how to report bugs effectively, please use this article as a guideline.

That's a *very* good article but I'm sure almost noone would read it before reporting an issue. They will just report an issue. But some people will read all of the CONTRIBUTING.md, then this article and then will report bugs better and cleaner. 

So, I think we should leave the info about posting bugs as is. The only point I have is to add info about debugging the extension and place for logs to issue template(of course while not removing this info from CONTRIBUTING.md).

**Comment by alexesprit** [comment]
> I think info about editorconfig should be added. Some devs can miss .editorconfig in the repo(especially if they didn't know about it before).

Editorconfig makes development easier, but it's not required since linters we use also follow `.editorconfig` options and they'll generate errors if proposed changes are unacceptable. That's why I didn't note Editorconfig in the guide. But it worth adding information about this.

> Another point is about connector development. I dunno if it does not contains enough info or people just don't read it properly but I see your points about simplifying connectors in many pull requests. That makes me sure that we need to add some common advices about connector development.

You're totally right. I noticed that too and I've already updated [this wiki page][1], that mentioned in the guide, and have added some valid/invalid code samples, that will be extended later.

> The only point I have is to add info about debugging the extension and place for logs to issue template(of course while not removing this info from CONTRIBUTING.md).

The issue template already contains this information.

[1]: https://github.com/david-sabata/web-scrobbler/wiki/Connectors-development

**Comment by alexesprit** [comment]
I noted EditorConfig in the contribution guide, and moved the block with examples of connector to the wiki page. I think all detailed information about connectors development should be placed in one place, and the wiki page fits perfectly for that.

**Comment by alexesprit** [comment]
Added in  7e345e59d1e34028763fa0d3f3e2fc46df82f739 and 975168c88e9d79a28078f4492d427bb0c9497786.
