### ISSUE TITLE
Specific track doesn't get recognised and can't add the details

### ISSUE THREAD

**Issue by Radiac93** [david-sabata/web-scrobbler#858]
I just get: " Play some music to get started" , even after opening the song in a new tab, refresh, etc.
Link to song: https://youtu.be/p0ljJj50y3k

**Comment by david-sabata** [comment]
I just tried and the track gets correctly recognized for me.

Can you re-authenticate with Last.fm (see the extension's options page) or eventually try reinstalling the extension?

**Comment by alexesprit** [comment]
I suppose the song isn't scrobbled because `Scrobble only Music category` option is enabled (just because it is not in Music category).
@Radiac93 have you tried to disable this option and scrobble the song again?

However, Web scrobbler looks up for song metadata (the magnifier icon is showing) even if song won't be scrobbled (like in this case). It might be confusing.

**Comment by Radiac93** [comment]
@alexesprit Yes that makes it work, but doesn't that mean it scrobbles *everything* I open on YouTube?
Sorry for the late reply, only got the mail to notify me the thread was closed.

Thanks for the help anyways!

**Comment by alexesprit** [comment]
> Yes that makes it work, but doesn't that mean it scrobbles everything I open on YouTube?

**Disabled** `Scrobble only Music category` option means 'scrobble everything'. Enabled one allows to scrobble from 'Music' category only.
