### ISSUE TITLE
London Burning scrobbling to last.fm

### ISSUE THREAD

**Issue by koukidis** [david-sabata/web-scrobbler#921]
Hello friends!
I am the responsible for London Burning web radio project for 5 years now.
It's an open project with no financial rewards that promote independent artists across the globe.
One of the trademarks of this radio is to highlight undiscovered tunes.
I could not succeed on installing the implementation on www.londonburning.net (wix platform) in order to enable users the scrobble action through the chrome add on.
I wonder if I could have your guidance on this.
Artists, listeners and I would feel really grateful to this assistance.
Best regards,
Nikolas Koukidis
www.londonburning.net
koukidis@londonburning.net

**Comment by Paszt** [comment]
I had a look but I don't think it's possible the way you currently have it setup due to the Marci iframes src being a different domain than the main page (www.londonburning.net.usrfiles.com versus http://www.londonburning.net/). XSS protection won't allow cross site content to be read by javascript.
